version: '3.8'

services:
  chatbot:
    build: .
    container_name: mysalak-chatbot
    volumes:
      - ./data:/app/data
      - ./db:/app/db
    environment:
      - OPENAI_API_KEY=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
    restart: unless-stopped 